# Generated by Django 3.1.12 on 2021-06-11 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20210608_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuatingdevice',
            name='light_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='measure_parameter',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
    ]
