# Generated by Django 3.1.12 on 2021-06-11 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_auto_20210611_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuatingdevice',
            name='light_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measure_value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
