# Generated by Django 3.1.12 on 2021-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0005_scheduledevicestate_light_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
