version: '3.8'

services:
  db:
    image: postgres:12
    env_file: .env
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - db
