version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:6.4.2
    volumes:
      - .:/code/elasticsearch
    ports:
      - "9200:9200"
  db:
    image: postgres:12
    env_file: ../../../bulbozaur-ps-03-database-graphql/.env
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ../../../bulbozaur-ps-03-database-graphql/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - db
      - elasticsearch
