name: project_skeleton
description: Skeleton, empty project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #printing graph
  draw_graph: ^1.0.0


  # CHECK NEW LIB'S VERSIONS AT PUB.DEV!
  # Core, code extensions
  dartz: ^0.10.0-nullsafety.1
  kt_dart: ^0.9.0
  logging: ^1.0.1
  path_provider: ^2.0.1
  supercharged: ^2.0.0

  #database
  flutter_secure_storage: ^4.2.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # Data & objects management
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

  # Dependency injection
  get_it: ^6.1.1
  injectable: ^1.3.0

  # Devices view testing todo before release comment it and remvoe
  device_preview: ^0.7.1

  # Widgets & UI Utils
  flutter_svg: ^0.21.0

  # State management & navigator
  auto_route: ^2.0.1
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.16.0
  sprintf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  auto_route_generator: ^2.0.1
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  hive_generator: ^1.1.0
  injectable_generator: ^1.3.0
  json_serializable: ^4.1.1

  # Testing
  mockito: ^5.0.5

    #Network
  http: ^0.13.3
  graphql_flutter: ^5.0.0-beta
  mqtt_client: ^9.3.1



flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/sounds/
    - assets/language/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - assets/images/png//a_dot_burr.png
    #   - assets/images/png//a_dot_ham.png

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: assets/fonts/Schyler-Regular.ttf
    #       - asset: assets/fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: assets/fonts/TrajanPro.ttf
    #       - asset: assets/fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
